#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += gn_w_sunwave/
#obj-y += gn_w_sunwave/
#obj-$(CONFIG_GOODIX_FINGERPRINT) += goodixfingerprint/
obj-$(CONFIG_HUAWEI_FINGERPRINT) += fingerprint/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
