include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom
ccflags-y += -Wno-error=declaration-after-statement -Wno-error=strict-prototypes -Wno-error=format-extra-args -Wno-error=unused-variable -Wno-error=unused-function
obj-y += imx278mipiraw_Sensor.o


